set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR cortex-m0plus)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(TOOLCHAIN_PREFIX arm-none-eabi CACHE STRING "GNU Arm Embedded toolchain prefix")

find_program(CMAKE_C_COMPILER NAMES ${TOOLCHAIN_PREFIX}-gcc REQUIRED)
find_program(CMAKE_ASM_COMPILER NAMES ${TOOLCHAIN_PREFIX}-gcc REQUIRED)
find_program(CMAKE_AR NAMES ${TOOLCHAIN_PREFIX}-ar REQUIRED)
find_program(CMAKE_RANLIB NAMES ${TOOLCHAIN_PREFIX}-ranlib REQUIRED)
find_program(CMAKE_OBJCOPY NAMES ${TOOLCHAIN_PREFIX}-objcopy REQUIRED)
find_program(CMAKE_SIZE NAMES ${TOOLCHAIN_PREFIX}-size REQUIRED)

set(CMAKE_EXECUTABLE_SUFFIX ".out")